// DO NOT EDIT THIS FILE
// This provides getAllEpisodes() for early levels

function getAllEpisodes() {
  return [
    {
      id: 1,
      name: "Winter Is Coming",
      season: 1,
      number: 1,
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_landscape/1/2668.jpg",
      },
      summary: "<p>Lord Eddard Stark is summoned to court...</p>",
    },
    {
      id: 2,
      name: "The Kingsroad",
      season: 1,
      number: 2,
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_landscape/1/2669.jpg",
      },
      summary: "<p>While Bran recovers from his fall...</p>",
    },
    {
      id: 3,
      name: "Lord Snow",
      season: 1,
      number: 3,
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_landscape/1/2670.jpg",
      },
      summary: "<p>Jon impresses Tyrion at Castle Black...</p>",
    },
  ];
}
